# Generated by Django 5.2.7 on 2025-10-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user_id',
            new_name='user',
        ),
    ]
