# Generated by Django 5.2.7 on 2025-10-20 10:05

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_id_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='from_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
