# Generated by Django 5.2.7 on 2025-10-20 10:26

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_appointment_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
